package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.kubernetesCloudImage
import jetbrains.buildServer.configs.kotlin.kubernetesCloudProfile
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            kubernetesCloudImage {
                id = "PROJECT_EXT_14"
                profileId = "kube-2"
                agentPoolId = "-2"
                maxInstancesCount = 2
                podSpecification = deploymentTemplate {
                    deploymentName = "teamcity-agent-linux-deployment"
                }
            }
        }
        add {
            kubernetesCloudProfile {
                id = "kube-2"
                name = "K8s agents"
                terminateIdleMinutes = 30
                apiServerURL = "https://A51B42A65F7E54005C95A4D353916627.gr7.eu-west-1.eks.amazonaws.com"
                authStrategy = eks {
                    accessId = "AKIA5JH2VERVI62P5XDY"
                    secretKey = "credentialsJSON:0875b686-8388-4392-8a90-7ae99948b35e"
                    clusterName = "tc-dkrupkina-eks-cluster"
                }
            }
        }
    }
}
